Vagrant.configure("2") do |config|
  # Specify the provider as libvirt
  config.vm.provider :libvirt do |libvirt|
    # Customize libvirt provider options if needed
    libvirt.memory = "200"
    # libvirt.cpus = 2
  end

  config.vm.synced_folder '../src', '/home/vagrant/src'
  # port forwarding, only if required
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.box = "centos/7"

  # Define the first VM - cnvm01
  config.vm.define "cnvm01" do |cnvm|
#    cnvm.vm.box = "centos/7"
    cnvm.vm.hostname = "cnvm01"

    # Configure private network with a static IP
    cnvm.vm.network "private_network", type: "dhcp", :ip => "192.168.121.10"
#    cnvm.vm.network "private_network", type: "dhcp"
  end

  # Define the remaining VMs - clvm01, clvm02, clvm03, clvm04
  (1..4).each do |i|
    config.vm.define "clvm0#{i}" do |clvm|
#      clvm.vm.box = "centos/7"
      clvm.vm.hostname = "clvm0#{i}"

      # Configure private network with static IPs
      #clvm.vm.network "private_network", type: "dhcp"
      clvm.vm.network "private_network", type: "dhcp", :ip => "192.168.121.#{i+10}"
    end
  end

  # Provisioning script for updating /etc/hosts and configuring passwordless SSH, installing and setting up ansible.
  #config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "bootstrap.sh", privileged: false
end
